const mockdb = {
  user: {
    username: 'user.name',
    avatar: 'User Name',
    currentBalance: 0,
    categories: {
      income: ['Salary', 'Rent'],
      spend: ['Utilities', 'Home/Rent', 'Car', 'Food/Groceries', 'Personal', 'Insurance/Medical', 'Entertainment', 'Misc/One-time']
    },
    transctions: {
      year2019: {
        januar: [
          {
            date: '',
            type: 'income',
            name: 'Salary',
            description: '',
            category: 'Salary',
            amount: 200,
            newBalance: 340,
          },
          {
            date: '',
            type: 'spend',
            name: 'Heating',
            description: '',
            category: 'Utilities',
            amount: 20,
            newBalance: 320,
          },
          {
            date: '',
            type: 'spend',
            name: 'Gasoline',
            description: '',
            category: 'Car',
            amount: 20,
            newBalance: 300,
          },
        ],
        februar: [
          {
            date: '',
            type: 'income',
            name: 'Salary',
            description: '',
            category: 'Salary',
            amount: 200,
            newBalance: 500,
          },
          {
            date: '',
            type: 'spend',
            name: 'Heating',
            description: '',
            category: 'Utilities',
            amount: 20,
            newBalance: 480,
          },
          {
            date: '',
            type: 'spend',
            name: 'Gasoline',
            description: '',
            category: 'Car',
            amount: 20,
            newBalance: 460,
          },
        ],
        march: [
          {
            date: '',
            type: 'income',
            name: 'Salary',
            description: '',
            category: 'Salary',
            amount: 200,
            newBalance: 660,
          },
          {
            date: '',
            type: 'spend',
            name: 'Heating',
            description: '',
            category: 'Utilities',
            amount: 20,
            newBalance: 640,
          },
          {
            date: '',
            type: 'spend',
            name: 'Gasoline',
            description: '',
            category: 'Car',
            amount: 20,
            newBalance: 620,
          },
        ]
      },
      year2018: {
        december: [
          {
            date: '',
            type: 'income',
            name: 'Salary',
            description: '',
            category: 'Salary',
            amount: 200,
            newBalance: 200,
          },
          {
            date: '',
            type: 'income',
            name: 'Rent',
            description: '',
            category: 'Rent',
            amount: 100,
            newBalance: 300,
          },
          {
            date: '',
            type: 'spend',
            name: 'Heating',
            description: '',
            category: 'Utilities',
            amount: 20,
            newBalance: 280,
          },
          {
            date: '',
            type: 'spend',
            name: 'Gasoline',
            description: '',
            category: 'Car',
            amount: 20,
            newBalance: 260,
          },
          {
            date: '',
            type: 'spend',
            name: 'Rent',
            description: '',
            category: 'Home/Rent',
            amount: 60,
            newBalance: 200,
          },
          {
            date: '',
            type: 'spend',
            name: 'Nagybevásárlás',
            description: '',
            category: 'Food/Grocerie',
            amount: 20,
            newBalance: 180,
          },
          {
            date: '',
            type: 'income',
            name: 'Stephen King - It',
            description: '',
            category: 'Personal',
            amount: 5,
            newBalance: 175,
          },
          {
            date: '',
            type: 'spend',
            name: 'Saridon',
            description: '',
            category: 'Medical/Health',
            amount: 5,
            newBalance: 170,
          },
          {
            date: '',
            type: 'spend',
            name: 'Gasoline',
            description: '',
            category: 'Car',
            amount: 20,
            newBalance: 150,
          },
          {
            date: '',
            type: 'spend',
            name: 'Mozi',
            description: '',
            category: 'Entertainment',
            amount: 10,
            newBalance: 140,
          },
        ]
      },
    }
  },
}


console.log(mockdb.user.transctions.year2019.march);
